/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as BacktestingRouteImport } from './routes/backtesting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'

const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingRoute = BacktestingRouteImport.update({
  id: '/backtesting',
  path: '/backtesting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtesting': typeof BacktestingRoute
  '/features': typeof FeaturesRoute
  '/matchup': typeof MatchupRoute
  '/performance': typeof PerformanceRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtesting': typeof BacktestingRoute
  '/features': typeof FeaturesRoute
  '/matchup': typeof MatchupRoute
  '/performance': typeof PerformanceRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtesting': typeof BacktestingRoute
  '/features': typeof FeaturesRoute
  '/matchup': typeof MatchupRoute
  '/performance': typeof PerformanceRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtesting'
    | '/features'
    | '/matchup'
    | '/performance'
    | '/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtesting'
    | '/features'
    | '/matchup'
    | '/performance'
    | '/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/backtesting'
    | '/features'
    | '/matchup'
    | '/performance'
    | '/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestingRoute: typeof BacktestingRoute
  FeaturesRoute: typeof FeaturesRoute
  MatchupRoute: typeof MatchupRoute
  PerformanceRoute: typeof PerformanceRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting': {
      id: '/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof BacktestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestingRoute: BacktestingRoute,
  FeaturesRoute: FeaturesRoute,
  MatchupRoute: MatchupRoute,
  PerformanceRoute: PerformanceRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
